#ifndef ELLIPTICALGAUSSLRF_GLOBAL_H
#define ELLIPTICALGAUSSLRF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ELLIPTICALGAUSSLRF_LIBRARY)
#  define ELLIPTICALGAUSSLRFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ELLIPTICALGAUSSLRFSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ELLIPTICALGAUSSLRF_GLOBAL_H
